//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMSStudyApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CEMSStudyApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_1 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_12 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_13 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_16 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_17 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_2 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_3 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_5 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_6 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_7 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_8 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS1_9 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS1_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_1 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_11 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_12 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_13 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_16 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_17 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_18 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_2 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_3 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_5 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_6 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_7 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS2_8 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS2_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_1 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_11 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_12 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_13 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_16 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_2 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_3 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_5 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_6 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_7 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS3_8 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS3_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_1 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_11 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_12 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_13 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_17 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_18 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_2 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_3 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_5 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_6 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_7 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4_8 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_1 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_11 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_13 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_16 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_17 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_17", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_18 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_2 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_3 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_5 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_6 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_7 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppB_PS4A_8 {
            get {
                object obj = ResourceManager.GetObject("AppB_PS4A_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P1_1 {
            get {
                object obj = ResourceManager.GetObject("AppF_P1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P1_2 {
            get {
                object obj = ResourceManager.GetObject("AppF_P1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P1_3 {
            get {
                object obj = ResourceManager.GetObject("AppF_P1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P1_4 {
            get {
                object obj = ResourceManager.GetObject("AppF_P1_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P1_5 {
            get {
                object obj = ResourceManager.GetObject("AppF_P1_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P1_6 {
            get {
                object obj = ResourceManager.GetObject("AppF_P1_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P1_7 {
            get {
                object obj = ResourceManager.GetObject("AppF_P1_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P1_8 {
            get {
                object obj = ResourceManager.GetObject("AppF_P1_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P1_F1 {
            get {
                object obj = ResourceManager.GetObject("AppF_P1_F1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P2_1 {
            get {
                object obj = ResourceManager.GetObject("AppF_P2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P2_10 {
            get {
                object obj = ResourceManager.GetObject("AppF_P2_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P2_11 {
            get {
                object obj = ResourceManager.GetObject("AppF_P2_11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P2_12 {
            get {
                object obj = ResourceManager.GetObject("AppF_P2_12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P2_2 {
            get {
                object obj = ResourceManager.GetObject("AppF_P2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P2_3 {
            get {
                object obj = ResourceManager.GetObject("AppF_P2_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P2_5 {
            get {
                object obj = ResourceManager.GetObject("AppF_P2_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P2_7 {
            get {
                object obj = ResourceManager.GetObject("AppF_P2_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppF_P2_9 {
            get {
                object obj = ResourceManager.GetObject("AppF_P2_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AppLogo {
            get {
                object obj = ResourceManager.GetObject("AppLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] No_Data_Available {
            get {
                object obj = ResourceManager.GetObject("No_Data_Available", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] No_Data_Available1 {
            get {
                object obj = ResourceManager.GetObject("No_Data_Available1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] No_Data_Available2 {
            get {
                object obj = ResourceManager.GetObject("No_Data_Available2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_10000 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_10000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100010 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100010", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100011 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100011", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100020 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100020", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100021 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100021", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100022 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100022", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100023 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100023", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100030 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100030", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100031 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100031", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100032 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100032", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100033 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100033", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100040 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100040", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100041 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100041", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_100042 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_100042", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_10005 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_10005", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_10006 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_10006", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_10007 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_10007", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_10009 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_10009", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_9980 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_9980", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_9981 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_9981", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_9982 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_9982", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_9983 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_9983", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_9984 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_9984", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_9985 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_9985", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_9990 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_9990", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_9991 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_9991", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Appendix_A {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Appendix_A", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Appendix_B {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Appendix_B", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Table_1 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Table_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Table_2 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Table_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Table_3 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Table_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Table_4 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Table_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Table_5 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Table_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Table_6 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Table_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Table_7 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Table_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Table_8 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Table_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_S_U_63_Table_9 {
            get {
                object obj = ResourceManager.GetObject("Part63_S_U_63_Table_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Appendix_A {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Appendix_A", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Appendix_B {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Appendix_B", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Table_1 {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Table_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Table_2 {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Table_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Table_3 {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Table_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Table_4 {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Table_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Table_5 {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Table_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Table_6 {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Table_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Table_7 {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Table_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Table_8 {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Table_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part63_SubpartUUUUU_Table_9 {
            get {
                object obj = ResourceManager.GetObject("Part63_SubpartUUUUU_Table_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_1_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_1_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_1_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_1_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_1_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_1_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_1_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_1_5_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_1_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_1_5_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_1_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_1_6 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_1_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_10_1_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_10_1_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_10_1_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_10_1_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_10_1_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_10_1_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_10_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_10_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_10_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_10_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_10_3_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_10_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_10_3_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_10_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_10_3_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_10_3_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_2_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_2_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_2_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_2_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_6 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_2_7 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_2_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_4_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_4_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_4_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_4_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_4_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_4_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_6 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_3_7 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_3_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_4_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_4_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_6 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_7 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_7_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_7_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_7_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_7_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_7_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_8 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_4_9 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_4_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_5_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_5_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_5_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_5_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_5_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_5_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_5_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_5_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_5_6 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_5_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_5_7 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_5_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_4_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_4_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_4_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_4_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_5_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_5_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_5_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_5_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_5_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_5_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_6 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_6_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_6_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_6_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_6_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_7 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_8 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_6_9 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_6_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_10 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_2_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_2_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_2_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_2_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_6 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_7 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_7_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_7_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_7_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_7_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_7_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_7_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_8 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_7_9 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_7_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_6 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_7 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_8 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_8_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_8_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_8_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_8_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_8_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_8_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_8_8_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_8_8_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_9_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_9_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_9_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_9_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_9_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_9_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_9_4 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_9_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_9_4_1 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_9_4_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_9_4_2 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_9_4_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_9_4_3 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_9_4_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_9_5 {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_9_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_AppendixA {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_AppendixA", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_AppendixB {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_AppendixB", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Part75_PE_AppendixC {
            get {
                object obj = ResourceManager.GetObject("Part75_PE_AppendixC", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
