//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMSStudyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acronym
    {
        public int AcronymsId { get; set; }
        public string Acronym1 { get; set; }
        public string AcronymFullName { get; set; }
    }
}
