//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMSStudyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcronymsLog
    {
        public int AcronymsLogId { get; set; }
        public string OriginalData { get; set; }
        public string NewData { get; set; }
        public string EditName { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    }
}
