//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMSStudyApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CEMS_Study_App_DbEntities : DbContext
    {
        public CEMS_Study_App_DbEntities()
            : base("name=CEMS_Study_App_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acronym> Acronyms { get; set; }
        public virtual DbSet<AcronymsLog> AcronymsLogs { get; set; }
        public virtual DbSet<Formula> Formulas { get; set; }
        public virtual DbSet<FormulasLog> FormulasLogs { get; set; }
        public virtual DbSet<HowTo> HowTos { get; set; }
        public virtual DbSet<HowTosLog> HowTosLogs { get; set; }
        public virtual DbSet<Part60> Part60 { get; set; }
        public virtual DbSet<Part60Log> Part60Log { get; set; }
        public virtual DbSet<Part75> Part75 { get; set; }
        public virtual DbSet<Part75Log> Part75Log { get; set; }
        public virtual DbSet<Password> Passwords { get; set; }
        public virtual DbSet<PasswordsLog> PasswordsLogs { get; set; }
    }
}
