//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMSStudyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formula
    {
        public int FormulasId { get; set; }
        public string FormulaName { get; set; }
        public string FormulaParameters { get; set; }
        public string FormulaDescription { get; set; }
    }
}
