//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CEMSStudyApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HowTo
    {
        public int HowTosId { get; set; }
        public string HowToName { get; set; }
        public string HowToDescription { get; set; }
    }
}
